import { CRMContact } from '../types';
import { ImportExportSchemaConfig } from './importExportEngine/types';

export const customerImportExportSchema: ImportExportSchemaConfig<CRMContact> = {
  moduleName: 'Customer',
  entityNameSingular: 'Customer',
  entityNamePlural: 'Customers',
  uniqueKeys: ['customerCode', 'email'],
  fields: [
    {
      key: 'customerCode',
      label: 'Customer Code',
      aliases: ['Code', 'Kode Pelanggan', 'Customer ID', 'ID Pelanggan', 'Cust Code'],
      required: true,
      type: 'string',
      example: 'CUST-005',
      description: 'Unique identifier code for the customer within organization',
    },
    {
      key: 'name',
      label: 'Full Name',
      aliases: ['Name', 'Nama', 'Nama Lengkap', 'Contact Name', 'Customer Name'],
      required: true,
      type: 'string',
      example: 'Alexander Vance',
      description: 'Full primary contact name',
    },
    {
      key: 'company',
      label: 'Company',
      aliases: ['Company Name', 'Perusahaan', 'Nama Perusahaan', 'Organization', 'Business'],
      required: false,
      type: 'string',
      example: 'Vance Dynamics',
      description: 'Company or business entity name',
    },
    {
      key: 'email',
      label: 'Email',
      aliases: ['Email Address', 'Alamat Email', 'E-mail', 'Contact Email'],
      required: true,
      type: 'email',
      example: 'a.vance@vancedynamics.io',
      description: 'Primary electronic email contact address',
    },
    {
      key: 'phone',
      label: 'Phone',
      aliases: ['Phone Number', 'No HP', 'Nomor Telepon', 'Telephone', 'Contact Phone', 'Mobile'],
      required: true,
      type: 'phone',
      example: '+1 (555) 018-9921',
      description: 'Primary telephone contact number',
    },
    {
      key: 'address',
      label: 'Address',
      aliases: ['Physical Address', 'Alamat', 'Street Address', 'Location'],
      required: false,
      type: 'string',
      example: '500 Tech Boulevard, Austin, TX',
      description: 'Street address location',
    },
    {
      key: 'stage',
      label: 'Pipeline Stage',
      aliases: ['Stage', 'Status Tahapan', 'CRM Stage', 'Sales Stage'],
      required: false,
      type: 'enum',
      enumValues: ['Lead', 'Contacted', 'Proposal Sent', 'Negotiation', 'Customer', 'Churned'],
      example: 'Customer',
      description: 'Current sales pipeline stage',
    },
    {
      key: 'status',
      label: 'Status',
      aliases: ['Account Status', 'Status Akun', 'State'],
      required: false,
      type: 'enum',
      enumValues: ['Active', 'Inactive'],
      example: 'Active',
      description: 'Account active or inactive state',
    },
    {
      key: 'dealValue',
      label: 'Deal Value',
      aliases: ['Value', 'Estimated Value', 'Nilai Transaksi', 'Nilai Deal', 'Amount'],
      required: false,
      type: 'number',
      example: 75000,
      description: 'Estimated commercial deal value in USD',
    },
    {
      key: 'notes',
      label: 'Notes',
      aliases: ['Interaction Notes', 'Catatan', 'Remarks', 'Description'],
      required: false,
      type: 'string',
      example: 'Key partner interested in enterprise deployment in Q4.',
      description: 'Interaction notes or special instructions',
    },
  ],
  sampleRows: [
    {
      'Customer Code': 'CUST-101',
      'Full Name': 'Siti Nurhaliza',
      'Company': 'Nusantara Retail Group',
      'Email': 'siti.n@nusantararetail.co.id',
      'Phone': '+62 812-3456-7890',
      'Address': 'Jl. Jendral Sudirman No. 45, Jakarta Selatan',
      'Pipeline Stage': 'Customer',
      'Status': 'Active',
      'Deal Value': 50000,
      'Notes': 'High potential enterprise buyer for IoT terminal units.',
    },
    {
      'Customer Code': 'CUST-102',
      'Full Name': 'Budi Santoso',
      'Company': 'Santoso Logistics Express',
      'Email': 'budi@santosoexpress.com',
      'Phone': '+62 811-9876-5432',
      'Address': 'Kawasan Industri Jababeka V, Cikarang',
      'Pipeline Stage': 'Negotiation',
      'Status': 'Active',
      'Deal Value': 35000,
      'Notes': 'Evaluating multi-warehouse fleet tracking system.',
    },
  ],
  transformToEntity: (mappedRow: Record<string, any>, organizationId: string): Partial<CRMContact> => {
    return {
      customerCode: String(mappedRow.customerCode || '').toUpperCase().trim(),
      name: String(mappedRow.name || '').trim(),
      company: String(mappedRow.company || 'N/A').trim(),
      email: String(mappedRow.email || '').trim(),
      phone: String(mappedRow.phone || '').trim(),
      address: String(mappedRow.address || '').trim(),
      stage: (mappedRow.stage as any) || 'Lead',
      status: (mappedRow.status as any) || 'Active',
      dealValue: Number(mappedRow.dealValue) || 0,
      notes: String(mappedRow.notes || '').trim(),
      organizationId,
      isDeleted: false,
      lastInteraction: new Date().toISOString().replace('T', ' ').substring(0, 16),
    };
  },
};
